### ISSUE TITLE
copy styles

### ISSUE THREAD

**Issue by parzivalliday** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#2]
i can't use this addon to copy styles. when i paste the style text to another anki field.it doesn't woks
<img width="721" alt="屏幕快照 2019-07-09 下午4 37 03" src="https://user-images.githubusercontent.com/52598401/60872738-d0355c80-a267-11e9-919a-cee3514d8edf.png">

**Comment by ijgnd** [comment]
### general point 
the add-on is not easy to setup. I plan to change this in a future version.

At the moment you have to follow the instructions from the [addon decription on ankiweb](https://ankiweb.net/shared/info/1899278645) under the heading `# styling with "class"`. You need another add-on and set it up. I added a screencast. maybe it helps: https://streamable.com/xtjqt

### when i paste the style text to another anki field.it doesn't woks

I can't reproduce this problem, see the end of my video. 

If you still have this problem: Update to the latest which is 2.1.14 and try again without any other add-ons: Disable all other add-ons or delete them, restart Anki and try again.

Does this solve the problem?

If not share your config and maybe also share a screencast.

**Comment by parzivalliday** [comment]
The problem is i can copy the font color, but i can't copy the **background** color.. i really need this feature😭here is the screen recording [https://streamable.com/vj60p](url)

**Comment by parzivalliday** [comment]
https://streamable.com/vj60p

**Comment by ijgnd** [comment]
thank's for screencast. This bug report is very useful for me.

This problem is caused by Anki 2.1. When you copy and paste from one field to another Anki 2.1 removes the bavckground-color tag with the javascript function `node.style.removeProperty("background-color");`  ([line 402 of the file editor.js from the folder web](https://github.com/dae/anki/blob/master/web/editor.js#L402)).

In Anki there's no way built in to change the background color so the fact that Anki removes it is not a problem of Anki. It's just that my add-on is not adjusted to Anki 2.1. I made this add-on for myself in 2.0 (where you can copy the background color) and so far I hadn't run into this limitation ...

A quick workaround would be to comment out the line I mentioned by adding `//` in front of it. But you would have to repeat it after every update.

A workaround would be to define a class `background_yellow` and set `.backcolor_yellow{background-color: yellow;}` in the template and _editor.css .

For existing code you could copy from the html source code view (ctrl+shift+x) and insert into the source code view in the other field. But this probably more time consuming than reapplying the styling ...

I need to think about this. Maybe the solution is to use only classes and make the configuration easier. But this might take some time. Maybe glutanimate will finally publish his html-cleaner add-on for 2.1 which allows an alternative paste which keeps more formatting.

**Comment by parzivalliday** [comment]
Thanks man.it works.
But when i use the anki2.0, I can't see the config.i cant set background color quickly with the keyboard shortcuts .sorry about my bad english..https://streamable.com/hj9rb

**Comment by ijgnd** [comment]
Only Anki 2.1 introduced the add-on configuration system.

In Anki 2.0 it's more complicated: You need to go to the add-on folder with the Finder (file manager), https://apps.ankiweb.net/docs/manual.html#file-locations . In the add-on folder there's a subfolder for my add-on and in it there's a file named `config.json` that you need to edit.
