### ISSUE TITLE
Cloze deletion does not preserve the style

### ISSUE THREAD

**Issue by skygate2012** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#3]
Generated cloze deletion will be excluded from the styles, as you can see from the image and code below.
![2019-08-29_21-55-53](https://user-images.githubusercontent.com/7148976/64077601-91220580-cd04-11e9-80a8-b662e3b67450.png)
![2019-08-29_21-56-08](https://user-images.githubusercontent.com/7148976/64077602-91220580-cd04-11e9-9bb4-183b05984b5b.png)

`<font color="#00aa00">This is&nbsp;</font>{{c1::green}}<font color="#00aa00">.</font>`

**Comment by ijgnd** [comment]
thanks for reporting this bug. 

I hadn't noticed it yet because I don't highlight clozes. I don't do this because Anki already highlights them during review.

I added this to my todo-list for the next version. But this will take a while. In the meantime the only way around I see is to apply the font color a second time after applying the cloze.

**Comment by ijgnd** [comment]
I just updated the add-on. I just tested and it seems that with the most recent version the styling isn't deleted by making a cloze.

If you are still interested you could help me test. Because of the many changes I made I didn't upload it to Ankiweb yet. The most recent version which is available [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/download/0.4/anki__editor__apply__font_color__background_color__custom_class__custom_style__2020-05-10.ankiaddon).

A guide for installing .ankiaddon files is [here](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation-macos.gif).

You need Anki 2.1.22 or newer for this version.

Before you test: Make sure to backup the old version of this add-on and know how to restore it.

If you find a bug or problem please let me know. At the moment I can't use my smartphone so maybe you could test that, too? Could you also check the html source of some formatted text? Do you have an interaction with other add-ons?

The default config needs improvements, especially for night mode values. If you have good suggestions ... If you have other ideas please let me know.

Thanks.

**Comment by skygate2012** [comment]
Thanks for updating. I tried it out but couldn't get it working though, the texts have no effect when applying colors. I'm running Anki 2.1.25 on Windows 10.
![dHIBUkhLw2](https://user-images.githubusercontent.com/7148976/81539004-24d2c800-93a2-11ea-9d53-388d26cee60b.gif)

**Comment by ijgnd** [comment]
Thank you very much. I only tested on my main computer (linux). Apparently the way I load and initialize the library for applying the class doesn't in windows or on other computers. I'll have to look into this. Thank you very much for the quick report. The screenshot was very useful. Sorry for wasting your time.

**Comment by skygate2012** [comment]
> 
> 
> Thank you very much. I only tested on my main computer (linux). Apparently the way I load and initialize the library for applying the class doesn't in windows or on other computers. I'll have to look into this. Thank you very much for the quick report. The screenshot was very useful. Sorry for wasting your time.

Oh I see. No worries, I'm glad to help :)

**Comment by ijgnd** [comment]
I have a new release [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/download/0.7/anki__editor__apply__font_color__background_color__custom_class__custom_style__2020-05-14.ankiaddon) with many changes (and improvements) which now also works on my windows computer.

Could you test again? Thanks. The general warnings (when testing a new add-on have backups etc.) still apply.

**Comment by skygate2012** [comment]
Now it works fine. Thank you so much. 

For night mode values, I think you can link the default colors and invert them by brightness, just like the invert colors option on Android.

**Comment by ijgnd** [comment]
Thanks for the feedback. Thanks for reminding me of the auto color adjustment feature of Ankidroid but sometimes I prefer my custom replacements. I'll add this to the todo list.
