### ISSUE TITLE
Edits I made are not transferring to new devices

### ISSUE THREAD

**Issue by chrisnerio** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#37]
I recently got a new computer and had to re-download anki as well as the add-on. In my old computer I had used the add-on extensively and made so many edits on cards using the shortcuts I made. However, I noticed immediately that since I got this new laptop that all the edits are gone (about ~5 to 10% are still there but very rarely). I downloaded everything on the new computer and then synced it. I then synced it to my phone and noticed they were also gone there as well. Is there any way to fix this?

If it helps-
The old computer (which is currently getting fixed) may have had an older version of Anki. I believe it was 2.1.31 and it was up to date as of 9/9/20 for the add-on updates. Could this be why? That's the only reason I see it failing. Of course, since I got this new computer this version is 2.1.33.

**Comment by ijgnd** [comment]
It's much more likely that the problem is that you changed your computer and reinstalled the add-on.

Did you modify the config on your old computer?

&nbsp;

Some background (the tldr is at the bottom):

Anki uses html in cards. In html you have different ways to apply styling. 

E.g. if I want to make some text red and bold I could write `style="font-weight: bold; color: red;"` directly into the source code of the field in a note. But you can also use  "classes" which my add-on often does. This means in the source code in the note I only have `class="bold_red"`. In a different (css) file I define just once how  "bold_red" should look like. This has some advantages, e.g. it's quick and easy to change the styling of many notes and this avoids some of the problems I described in the quirks sections on [ankiweb](https://ankiweb.net/shared/info/1899278645).

I think as a user you shouldn't have know about technical details such as classes, css etc. So my add-on tries to hide some of this complexity, e.g. you usually don't have to manually set a class name. So you likely also used classes and maybe without knowing it.

&nbsp;

When you install the add-on, whenever you open your profile, and whenever you open and close the config of my add-on it writes the config values related to the styling of classes to the external css file. 

But this is a one-way street: My add-on does not read the config from this external css file: Css files are only used to set the styling/appearance for html but my add-on needs additional info like which shortcuts to use etc.

&nbsp;

You switched to the new computer. You re-installed my add-on from ankiweb. So on your new computer you get the default config and this default config is written into the external css file. If you had a custom config it's likely that some or most of your entries technically relied on classes. The class-names used in the old config are no longer in your new config and so the add-on can't save any styling to the external css files for the classes from the old config. 

So when Anki displays a note or card on your new computer it detects a class and checks the css file but since it doesn't find any special settings for said class in the css file it doesn't modify the styling. So it's visually broken.

&nbsp;

**How to restore the old config: (Tldr)**: 
- If your old computer still works it's easy: You can export your old config from your old computer from the config of my add-on by clicking the "More" button and then selecting "Export Button Config to json". Then import this file on the new computer with "More"->"Import Button Config to json". Then everything should work.
- If you have a backup of your add-on folder you could use your backup software to restore the whole add-on folder. It's tedious to copy over and reapply all user settings for each software you use. So all people I know just restore their whole user folder from their backup, e.g. on MacOS you'd just use your TimeMachine drive. All your add-ons are in your user folder so such a full restore also gives you back all your add-ons with your custom configurations.
- If you don't want to do a full restore of all user data you can just copy over one file: Exit/Close Anki on your new computer. Then you can copy over the file `1899278645/user_files/settings.pypickle` from your old computer's add-on folder to the same location on your new computer. How to find your add-on folder: https://docs.ankiweb.net/#/files?id=file-locations
- If you don't have a backup it's more complicated: It is not enough to recreate the same styling options - the class names must also match and my add-on sometimes hide the class names so that it's less confusing to users. The downside is that in your situation you can't rely on the add-on config dialog to set the old class names. So you would need a workaround: You would have to export the styling to json, then edit the file with a text editor and then re-import it. This is quite complicated but I assumed that each user has a backup. You would have to check the html source code of your fields

**Comment by ijgnd** [comment]
Does this solve your problem?

If you don't understand some parts of the prior post let me know which parts should be more clear.

**Comment by chrisnerio** [comment]
thank you for all the information! Unfortunately I just got my computer back and it was wiped completely. I unfortunately do not have any backups so from now on that's something that I am going to have to do.

It sounds like the last option you gave me can be possible? If you think it is possible and it can potentially help my situation would you mind elaborating on how I can do that. I am currently using a mac. Thank you again for the time you took to write that!

**Comment by chrisnerio** [comment]
I actually just fixed it. I had a picture of my old config settings and just copied them and somehow all the colors reappeared!
