### ISSUE TITLE
MacOs issue- Config shows up when selecting "Anki Preferences"

### ISSUE THREAD

**Issue by chrisnerio** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#38]
The config for the add-on pops up every time I click on Anki Preferences.

I have tried this on both of my computers.

Below is a video of the problem.

[Bug.zip](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/files/5241294/Bug.zip)

**Comment by ijgnd** [comment]
@chrisnerio: We had a similiar issue some months ago, see [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/issues/12). I think I have reintroduced the bug because when changing the add-on name to "custom Styles" I set the action name to "Config for Custom Styles". I don't have a Mac but @hgiesel does. He's the new maintainer of this add-on.

**Comment by hgiesel** [comment]
Yep, I also noticed the bug re-emerging. I'll work on it later today.

**Comment by hgiesel** [comment]
@chrisnerio I just pushed a new version which fixes this bug. You can update right away.
