### ISSUE TITLE
Media references are not refreshed upon restart

### ISSUE THREAD

**Issue by hgiesel** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#5]
I recently noticed a bug when updating your `_editor_button_styles.css`. It seems like Anki doesn't recognize that the file was updated, and won't upload it to AnkiWeb, which means the file won't be updated on AnkiMobile (and possible AnkiDroid).

With 2.0 this behavior could be fixed with an app like this: https://ankiweb.net/shared/info/162278717. However it doesn't work on 2.1. I'm sure this could be replicated in 2.1.

**Comment by ijgnd** [comment]
Thanks for this report. I didn't properly test this when I released the add-on. So the add-on that is published on Ankiweb also for me has the problem that changes aren't uploaded to ankiweb if between syncs I only change the `_editor_button_styles.css` file from my config dialog.

I just added a change and tested it with with Anki 2.1.15 (flatpak) on linux and the latest ankidroid from the playstore. I copied from the linked [Refresh Media References](https://ankiweb.net/shared/info/162278717) at the end of my function [updateConfig](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/master/src/config.py#L660) this code:

        media_dir = mw.col.media.dir()
        fpath = os.path.join(media_dir, "syncdummy.txt")
        if not os.path.isfile(fpath):
            with open(fpath, "w") as f:
                f.write("anki sync dummy")
        os.remove(fpath)

This still seems to be the official solution to trigger an update of the media dir, see [this line in media.py](https://github.com/ankitects/anki/blob/master/pylib/anki/media.py#L464)?

With this updated code in my setup changes to `_editor_button_styles.css` seem to be synced to my ankidroid: Between syncs the only thing I changed was one color in my add-on config. So glutanimate's code seems to fix the sync problem for me.

But you write "However it doesn't work on 2.1". So I assume that changes to my css file are not synced between your computer and your ios device? I'll have to read up on this and try to get an ios device.

&nbsp;


Updating the styling is not directly visible in all parts of Anki on the desktop. That's why I have the showInfo function that reminds a user to restart Anki. Actually the reviewer uses the most recent styling if you reload the reviewer, e.g. by going to the main screen and back to reviews. But I was too lazy to do something for the editor. I only modify the Editor class when you start Anki (see [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/master/src/color_style_class_buttons.py#L230)). Fixing this would require more work since other add-ons also modify editor._html. So it's not about clearing a cache. (P.S. to clear the webengine cache I use [editor.web.page().profile().clearHttpCache()](https://github.com/ijgnd/anki21__OpenInExternalEditor_Rename_Duplicate_for_Image_Audio_Video/blob/master/src/editExternal.py#L101) in my "OpenInExternalEditor" add-on). But I guess your report didn't refer to this.

&nbsp;

You already made the add-on much better. I'm looking forward to merging your other enhancements/improvements (see #4). Thanks for your help.

**Comment by ijgnd** [comment]
I just tried with an old ios device running ios9. 

In my Ankimobile version I sync from the deck list screen. After a sync I click on a deck and start reviewing. Then the updated stylesheet is not applied as you described.

If after a sync I force close ankimobile and reopen it then the proper stylesheet is loaded. I don't see anything else I can do? Apparently ankimobile reuses the same webview longer. 

Does force close and reopen Ankimobile also help on your more modern ios device with a more recent Ankimobile?

Do you have a better idea than mentioning this workaround in the manual?

With "force close" I mean: double click the home button, then swipe up on the app's preview

**Comment by hgiesel** [comment]
Just tested it. Works now without any hiccups.
