### ISSUE TITLE
Categories "Backcolor (via class)" and "class" sometimes do not apply the class, but style

### ISSUE THREAD

**Issue by hugomarins** [ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style#7]
I think there is a bug in the "Backcolor (via class)" and "class" categories.

Sometimes they work applying "class=..." inside the <span> tag. E.g.: <span class="yb">.

But other times, especially when we do not select the entire paragraph, it just apply the styling which has been configured to the class (and is on the _editor_button_styles.css file. E.g. <span style="background-color: chocolate;">.

Why does it happen?

**Comment by ijgnd** [comment]
it's complicated, my knowledge in this area is limited. Very important: When I made this add-on Anki lacked features to easily load custom js files into the editor so it was more complicated. The benefit of this is limited since this only rarely happens to me so I was not motivated to spend too much time on it. I think I have a solution for the most recent anki version but it might take a while until I update the add-on.

**Comment by ijgnd** [comment]
I just updated the add-on. Because of the many changes I made I didn't upload it to Ankiweb yet. It would be great if you could test the most recent version which is available [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/download/0.4/anki__editor__apply__font_color__background_color__custom_class__custom_style__2020-05-10.ankiaddon).

A guide for installing .ankiaddon files is [here](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation-macos.gif).

As I said: You need Anki 2.1.22 or newer for this version.

Before you test: Make sure to backup the old version of this add-on and know how to restore it.

For details: Before todays version when trying to apply a class I just put `<span class="somename">` and `</span>` around the text the user selected, see [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/blob/4bd1bb62bcabb68824823ce34271cc685e17c7eb/src/editor_apply_styling_functions.py#L84). If the selection covered multiple html tags this didn't work. Now with Anki 2.1.22 I can easily use an external helper library that should properly style each selected tag.

Could you also check the html source of some formatted text? Do you have an interaction with other add-ons? If you find a bug or problem please let me know. The default config needs improvements, especially for night mode values. If you have good suggestions ... If you have other ideas please let me know.

Thanks.

**Comment by ijgnd** [comment]
At the moment my smartphone doesn't work so I can't test on mobile. So a test on mobile would also help.

**Comment by hugomarins** [comment]
Hi ijgnd, I installed the update you made, but its not working for me. I'm using Anki 2.1.24 (Windows). The installation was successful, I created some "class (others)" in the config, everything works.

But when I go to add a card, select some text and use the shortcuts, nothing happens, doesn't matter what kind of class I'm trying to apply. Using the menu also doesn't work. Nothing is applied to the selection.

I tried to disable some of my add-ons that I thought may be in conflict, but it didn't hep.

I have many add-ons, I'll send you the debug info; maybe one of them is in conflict, but maybe there is an issue in the add-on.

I don't know how to program, but I will help as much as I can. if you need any additional test or info, just let me know.

Thanks,

Hugo.

Debug Info:
    
    Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-05-10 19:47:20
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2020-04-03T13:06, 'None', '']
    Add Table ['1237621971', 2020-04-27T17:52, 'None', mod]
    Advanced Browser ['874215009', 2020-04-22T19:45, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-09-24T08:01, 'None', '']
    Anki Simulator ['anki_simulator', 2020-03-28T16:47, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', mod]
    Answer Confirmation for 21 ['1354051622', 2019-09-24T08:34, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-04-14T09:51, 'None', '']
    Batch Editing ['291119185', 2019-09-24T07:39, 'None', '']
    BetterTags ['bettertags', 2020-04-28T12:40, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T09:37, 'None', '']
    Copy notes ['1566928056', 2020-03-11T21:56, 'None', mod]
    Create Filtered Deck from the Browser ['861263371', 2019-09-24T08:34, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2020-03-11T02:05, 'None', '']
    Deck name in title 21 ['699175524', 2019-09-24T08:37, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-04-28T23:30, 'None', mod]
    Enhance main window ['877182321', 2020-05-03T13:58, 'None', mod]
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T14:42, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-09-24T07:41, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2019-09-24T07:45, 'None', '']
    Hitmarkers ['1776869150', 2020-03-31T19:04, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Keep model of add cards ['424778276', 2020-05-04T18:14, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2019-09-24T07:46, 'None', '']
    Large and Colorful Buttons ['1829090218', 2019-11-16T22:31, 'None', '']
    Mini Format Pack ['295889520', 2019-09-24T07:40, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-03-31T17:19, 'None', '']
    More Overview Stats 21 ['738807903', 2019-09-24T08:22, 'None', '']
    Multiple Choice for Anki ['1566095810', 2020-04-10T02:50, 'None', '']
    Opening the same window multiple time ['354407385', 2020-03-09T08:57, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T09:35, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-09-24T08:33, 'None', '']
    Quick Colour Changing ['2491935955', 2019-09-24T08:35, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v140 ['323586997', 2020-04-17T04:07, 'None', mod]
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T17:13, 'None', '']
    Show fields source html in editor ['1574324795', 2020-03-28T04:08, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T06:11, 'None', '']
    Spell Checker ['spell_checker', 0, 'None', '']
    Symbols ['1461102936', 2019-09-24T08:35, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2020-05-08T10:16, 'None', '']
    deck and card info sidebar during review ['673114053', 2020-05-04T09:06, 'None', mod]
    editor: apply font color, background color, custom class, custom style ['1899278645', 2020-05-10T15:41, 'None', '']
    export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2020-05-04T11:00, 'None', '']
    extended table editor ['805891399', 2020-04-28T05:01, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1237621971 1354051622 1374772155 1461102936 153625306 1556734708 1566095810 1566928056 1574324795 1776869150 1807206748 1829090218 1898445115 1899278645 1967530655 2084557901 225180905 24411424 2491935955 291119185 295889520 318752047 323586997 354407385 385888438 424778276 538879081 561945101 673114053 699175524 738807903 805891399 814349176 861263371 874215009 877182321
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
      Advanced Review Bottom Bar   ['1136455830', 2020-05-09T00:26, 'None', mod]
    Advanced Card Styles ['1625103157', 2019-09-24T08:25, 'None', '']
    Customize Editor Stylesheet ['1215991469', 2019-09-24T09:07, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T18:01, 'None', '']
    Editor Autocomplete ['924298715', 2020-01-18T07:02, 'None', '']
    Export cards selected in the Browser ['1983204951', 2020-02-03T13:31, 'None', '']
    Graphical form to change add-on configuration ['1014777615', 2020-03-19T07:22, 'None', '']
    Newline in strings in add-ons configurations ['112201952', 2020-03-19T15:41, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-03-02T16:22, 'None', mod]
    Show LaTeXs result in editorbrowser ['882784122', 2020-03-26T12:58, 'None', '']
    Trigger and actions change one card depending on what occurs on another card ['1981494159', 2020-05-04T17:53, 'None', mod]
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T16:43, 'None', mod]

**Comment by ijgnd** [comment]
Thanks for the testing and the quick report.

I only tested on my main computer (linux). Apparently the way I load and initialize the library for applying the class doesn't work in windows or maybe it doesn't work on other computers at all? This is not an interaction with other add-ons as far as I see. I'll have to look into this. When I have a solution I'll post again. Sorry for wasting your time.

**Comment by hugomarins** [comment]
No problem at all. If you need me to test anything else, just ask. I'm at your service. This particular add-on is very important to me!

**Comment by ijgnd** [comment]
I just made a new version that works on my two computers in Windows and Linux. 

It's [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/tag/0.5). The warnings, caveats, etc. from yesterday still apply - a very visible shortcoming still is that the defaultconfig has duplicate entries etc.

Does this work for you? 

Thanks for testing & feedback.

**Comment by hugomarins** [comment]
Hi @ijgnd 

Thanks for being so quick. I tested you add-on and it is really good! I saw that you can now apply classes without losing the formatting already in the selected portion of text. It is working really well.

A point I observed is that using Ctrl+Z is not undoing the formatting applied by the add-on anymore. It would be good to have it, in case you discover you did something wrong.

And the "class (other)" just apply the class by using the <span> tag :( I know the need for applying <div> classes probably is not a need of many people, but I strongly use "extra" field info to provide context in my cards, and in them I use the div classes to create boxes (by using borders and background colors) for standardized information, such as:

- A brown border and yellow background box means that its content is a quotation of another author or material of my studies, that somehow complement the same information [I also use fields for classifying the books, as I am studying to a test for getting a position, and the references to be used are determined, and I need to know who says what, so it helps me to create these synapses];
- A red border and light red background means a quotation of another author that contradicts the information of that card;
- A green border with an image background means that its content is a mnemonic for helping me remember the content of the card.
And so on. And there is not how to create boxes via <span>! It is so important to me that in your previous version of the add-on, I changed the code (even not knowing how to code!) to create another class, just like the span class, but writing <div> instead of <span>. It was working for me!! Your add-on saves me a lot of time; before it, I needed to open the html code and try to find in a long text the exact point to insert the <div> tag, and type it manually. It took a lot of time!

Anyway, your add-on is working very well! If you need something, keep in touch. 

Thanks.

**Comment by ijgnd** [comment]
I just made a new release [here](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/releases/download/0.7/anki__editor__apply__font_color__background_color__custom_class__custom_style__2020-05-14.ankiaddon).

I made substantive changes: I changed again how the underlying js library is loaded. Now you need 2.1.22 again. Does this work for you?

if it does: I re-added the option to use inline styling and also an option to surround your span class with a div and an option to just wrap with a div. Could you test many different config options and if it works on mobile?

Thank you very much.

**Comment by hugomarins** [comment]
Sorry for taking this long to see this. Just tell me if I must use Anki 2.1.22 or if is ok to use the last stable version (Anki 2.1.26). I'm using 2.1.26 and the add-on appears to create a conflict. Just tell me this and I'll keep testing.

**Comment by ijgnd** [comment]
I want it to work on 2.1.26. Could you describe the problem: what happens, what do you see, do you get some error message?

also:  From the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

**Comment by hugomarins** [comment]
The error was happening as soon as I open my Anki. But I realized that the problem could be in the conversion from my old configs to the new version, and so I uninstalled the previous version and then installed the new one and reset my config.  Doing this, the problem disappeared.

You add-on is working perfectly in Anki 2.1.26. I tested specifically applying background via class and applying div class. It worked perfectly!

By the way, thank you very much for inserting the option of applying classes to div tags!!

As far as I can see, there is no more conflict between you add-on and the "Customize Editor Stylesheet". I still use it and I don't use the "Updating templates" option of your add-on, just because I have many note types and I already was using a "@import  url" in the style section of all my cards type, and indeed I had lots of pre-set styling for many other purposes. I really don't know if Anki would accept importing styles of more than one file. 

But it is working ok, because your add-on applies the tags in the html, and latter the editor and reviewer search the styling in that file I already have.

But, because of this, I think I'm not the best tester for the mobile, as you asked, as by my configs the styling would be searched in a different file from that of your add-on.

Anyway, I can keep testing things that you ask, ok?

Thanks!

**Comment by ijgnd** [comment]
Thanks for the feedback.

My add-on should work with old configs. Without knowing details there's nothing I can do. If you still have the old config, e.g. in a backup, it would be great if you could send it to me or upload it as an attachment:  Just zip the folder for this add-on in your addons21 folder. I ask for the whole folder because I don't use the meta.json for storing it, instead i use a file named "settings.pypickle" in the user_files subfolder of the add-on. This would help a lot.

&nbsp;

It's supposed to work with the "editor stylesheet" add-on now. Actually I have an improved version of the "editor stylesheet" add-on [here](https://github.com/ijgnd/anki__customize_editor_stylesheet): This version has these improvements:

- config changes are applied without restarting (using the new hooks from 2.1.22)
- detects Anki's built-in night mode (for styling the tag bar in the editor)
- a built-in mini editor for quickly editing the stylesheet file.

Could you test this version and let me know if you have a problem with it (best in the issue section for this add-on).

The auto updating of the templates should not interfer with the "editor stylesheet" add-on: In my styling section I have two lines:

    @import url("_editor.css"); 
    @import url("_editor_button_styles.css");

Anki accepts importing styles from more than one file. It would be great if you could test if the auto updating of the templates work and if the add-ons work well together. Make sure to have a backup first ...

**Comment by hugomarins** [comment]
Fist of all, thanks for the fork version of "editor stylesheet". 

I did as you asked and auto updated all my templates. Indeed there is no conflict with the other css file imported by my templates. It's working perfectly.

Don't care about the conflict (when I updated to this last version) with my old config that I related. Remember that I changed slightly the code and also the config file, creating a category that was not in your original add-on. I think this is the cause of the problem.

Now that I know Anki can deal with more than one css imported file in the templates, I'll test better how are things going on my mobile (AnkiDroid) and let you know if there is any issue.

Thanks for all!
